apiVersion: apps/v1
kind: Deployment

metadata:
  name: ecommerce-app
  namespace: ecommerce

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ecommerce

  template:
    metadata:
      labels:
        app: ecommerce

    spec:
      containers:
      - name: ecommerce-container

        image: 271758792051.dkr.ecr.eu-north-1.amazonaws.com/ecommerce:v2

        imagePullPolicy: Always

        ports:
        - containerPort: 5000

        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: APP_NAME

        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: APP_VERSION

        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: ENVIRONMENT

        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: ecommerce-secret
              key: DB_USERNAME

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecommerce-secret
              key: DB_PASSWORD
